import {readFile, writeFile} from 'node:fs/promises';
import {resolve, dirname, relative, isAbsolute} from 'node:path';
import {fileURLToPath} from 'node:url';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const catalog = JSON.parse(await readFile(resolve(root,'edge_form_graph/control_catalog.json'),'utf8'));
const names = new Set();
const imports = [], entries = [];
function checkedImport(spec, alias, library) {
  const base=resolve(root,'browser/controls'), path=resolve(base,spec.implementation);
  const rel=relative(resolve(root,'browser',library),path);
  if(isAbsolute(rel)||rel.startsWith('..')||!/^[A-Za-z_$][\w$]*$/.test(spec.export))throw new Error('invalid_library_path');
  imports.push(`import {${spec.export} as ${alias}} from ${JSON.stringify(spec.implementation)};`);
}
for (const [i, control] of catalog.controls.entries()) {
  if (!control.name || names.has(control.name)) throw new Error('duplicate_control_name');
  names.add(control.name);
  if(Object.hasOwn(control,'match'))throw new Error('recognition_belongs_in_rule_library');
  checkedImport(control,`driver${i}`,'controls');
  if(!Array.isArray(control.rules)||!control.rules.length)throw new Error('control_rules_required');
  const rules=control.rules.map((rule,j)=>{
    if(!['control','field','manual'].includes(rule.route))throw new Error('invalid_rule_route');
    checkedImport(rule,`rule${i}_${j}`,'rules');
    return `{match:rule${i}_${j},route:${JSON.stringify(rule.route)}}`;
  });
  entries.push(`[${JSON.stringify(control.name)}, {driver:driver${i}, config:${JSON.stringify(control)}, rules:[${rules.join(',')}]}]`);
}
const source = '// Generated by scripts/build_control_registry.mjs. Do not edit.\n' + imports.join('\n') +
  `\nexport const protocolVersion = ${catalog.protocolVersion};\nexport const registryVersion = ${catalog.registryVersion};\n` +
  `export const entries = new Map([\n${entries.join(',\n')}\n]);\n`;
const output = resolve(root,'browser/controls/registry.generated.mjs');
if (process.argv.includes('--check')) {
  if (await readFile(output,'utf8') !== source) throw new Error('CONTROL_REGISTRY_MISMATCH: generated registry is stale');
} else await writeFile(output, source);
